server:
  port: 8002
spring:
  application:
    name: stock-service
  redis:
    database: 0
    # Redis服务器地址 写你的ip
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 49153
    # Redis服务器连接密码（默认为空）
    password: redispw
    # 连接池最大连接数（使用负值表示没有限制  类似于mysql的连接池
    jedis:
      pool:
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 表示连接池的链接拿完了 现在去申请需要等待的时间
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
    # 连接超时时间（毫秒） 去链接redis服务端
    timeout: 3000
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#    sentinel:
#      transport:
#        dashboard: 127.0.0.1:8081
#        # 当前应用被sentinel监控的端口
#        port: 8720

#mybatis:
#  type-aliases-package: com.qianyitian.hope2.stock.model

logging:
  file:
    name: ./log/stock.log
  level:
    root: INFO

hope2:
  service:
    spider: http://127.0.0.1:8001
    stock: http://127.0.0.1:8002
    analyzer: http://127.0.0.1:8003
  data:
    path: ./target/data
